# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_number', models.CharField(max_length=20, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe7\xbc\x96\xe5\x8f\xb7')),
                ('course_name', models.CharField(max_length=20, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('nature', models.CharField(choices=[(b'compulsory ', b'\xe5\xbf\x85\xe4\xbf\xae\xe8\xaf\xbe'), (b'optional', b'\xe9\x80\x89\xe4\xbf\xae\xe8\xaf\xbe')], max_length=20, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x80\xa7\xe8\xb4\xa8')),
                ('credit', models.SmallIntegerField(verbose_name=b'\xe5\xad\xa6\xe5\x88\x86')),
                ('hour', models.SmallIntegerField(verbose_name=b'\xe5\xad\xa6\xe6\x97\xb6')),
                ('teacher', models.CharField(max_length=10, verbose_name=b'\xe6\x8e\x88\xe8\xaf\xbe\xe6\x95\x99\xe5\xb8\x88')),
                ('year', models.SmallIntegerField(verbose_name=b'\xe5\xad\xa6\xe5\xb9\xb4')),
                ('term', models.SmallIntegerField(verbose_name=b'\xe5\xad\xa6\xe6\x9c\x9f')),
                ('start_week', models.SmallIntegerField(verbose_name=b'\xe8\xb5\xb7\xe5\xa7\x8b\xe5\x91\xa8')),
                ('end_week', models.SmallIntegerField(verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe5\x91\xa8')),
                ('content', models.SmallIntegerField(verbose_name=b'\xe5\xae\xb9\xe9\x87\x8f')),
                ('place', models.CharField(max_length=10, verbose_name=b'\xe4\xb8\x8a\xe8\xaf\xbe\xe5\x9c\xb0\xe7\x82\xb9')),
            ],
            options={
                'ordering': ['course_number'],
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14')], max_length=4, verbose_name=b'\xe8\x8a\x82\xe6\x95\xb0')),
                ('weekday', models.CharField(choices=[(b'1 ', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x80'), (b'2', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x8c'), (b'3', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x89'), (b'4', b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x9b\x9b'), (b'5', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x94'), (b'6', b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x85\xad'), (b'7', b'\xe6\x98\x9f\xe6\x9c\x9f\xe6\x97\xa5')], max_length=10, verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'ordering': ['course'],
                'verbose_name': '\u8bfe\u7a0b\u65f6\u95f4\u5b89\u6392',
                'verbose_name_plural': '\u8bfe\u7a0b\u65f6\u95f4\u5b89\u6392',
            },
        ),
    ]
