# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_number'], 'verbose_name': '\u67e5\u770b\u8bfe\u7a0b', 'verbose_name_plural': '\u67e5\u770b\u8bfe\u7a0b'},
        ),
    ]
