# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170104_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['lesson'], 'verbose_name': '\u8bfe\u7a0b\u65f6\u95f4\u5b89\u6392', 'verbose_name_plural': '\u8bfe\u7a0b\u65f6\u95f4\u5b89\u6392'},
        ),
        migrations.AlterField(
            model_name='time',
            name='weekday',
            field=models.CharField(choices=[(b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x80', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x80'), (b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x8c', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x8c'), (b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x89', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x89'), (b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x9b\x9b', b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x9b\x9b'), (b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x94', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x94'), (b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x85\xad', b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x85\xad'), (b'\xe6\x98\x9f\xe6\x9c\x9f\xe6\x97\xa5', b'\xe6\x98\x9f\xe6\x9c\x9f\xe6\x97\xa5')], max_length=10, verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
