# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170306_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='weekday',
            field=models.CharField(choices=[(b'1', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x80'), (b'2', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x8c'), (b'3', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xb8\x89'), (b'4', b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x9b\x9b'), (b'5', b'\xe6\x98\x9f\xe6\x9c\x9f\xe4\xba\x94'), (b'6', b'\xe6\x98\x9f\xe6\x9c\x9f\xe5\x85\xad'), (b'7', b'\xe6\x98\x9f\xe6\x9c\x9f\xe6\x97\xa5')], max_length=10, verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
