# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stucourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name=b'\xe6\x88\x90\xe7\xbb\xa9')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'ordering': ['course'],
                'verbose_name': '\u6210\u7ee9\u5f55\u5165',
                'verbose_name_plural': '\u6210\u7ee9\u5f55\u5165',
            },
        ),
    ]
