# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-30 10:19
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('student_number', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7')),
                ('student_name', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xa7\x93\xe5\x90\x8d')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d')),
                ('classes', models.CharField(max_length=20, verbose_name=b'\xe7\x8f\xad\xe7\xba\xa7')),
            ],
            options={
                'ordering': ['student_number'],
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_number', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe9\x99\xa2\xe7\xbc\x96\xe5\x8f\xb7')),
                ('department_name', models.CharField(max_length=20, verbose_name=b'\xe5\xad\xa6\xe9\x99\xa2\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'ordering': ['department_number'],
                'verbose_name': '\u5b66\u9662',
                'verbose_name_plural': '\u5b66\u9662',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.AutoField(primary_key=True, serialize=False)),
                ('major_number', models.CharField(max_length=20, verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe7\xbc\x96\xe5\x8f\xb7')),
                ('major_name', models.CharField(max_length=20, verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'ordering': ['major_number'],
                'verbose_name': '\u4e13\u4e1a',
                'verbose_name_plural': '\u4e13\u4e1a',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='student.Department', verbose_name=b'\xe5\xad\xa6\xe9\x99\xa2\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='student.Major', verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
