# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-04 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='classes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\x8f\xad\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Department', verbose_name=b'\xe5\xad\xa6\xe9\x99\xa2\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Major', verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xa7\x93\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7'),
        ),
    ]
